version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - mysql_data:/var/lib/mysql
      - bundle_install:/usr/src/app/vendor/bundle
      - bundle:/usr/src/app/.bundle
  db:
    image: mysql:5.7.19
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes_from:
      - datastore
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      DATABASE_HOST: 'db'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: ''
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes_from:
      - datastore
volumes:
  mysql_data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
